---
downloads: ~/.ansible-downloads/
mount_path: /Volumes

# set to yes to run certain tasks
configure_aws: yes
configure_chef: yes
configure_dotfiles: yes
configure_helm: yes
configure_sudoers: no
configure_terminal: yes
configure_osx: yes
configure_vim: yes
configure_vscode: yes

dotfiles_repo: "git@github.com:chrisminton/dotfiles.git"
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/personal/dotfiles
dotfiles_files:
  - .gitignore
  - .config/powerline
  - .k9s/plugin.yml
  - .osx
  - .ssh/config
  - .tmux.conf
  - .vimrc
  - .zshrc

homebrew_installed_packages:
  - autoconf
  - awscli
  - aws-shell
  - azure-cli
  - bash
  - bash-completion
  - coreutils
  - cowsay
  - derailed/k9s/k9s
  - direnv
  - dive
  - fluxcd/tap/flux
  - fzf
  - gh
  - git
  - git-duet
  - gnu-tar
  - go
  - gpg
  - helm
  - httpie
  - iperf
  - jq
  - kind
  - krew
  - kubectx
  - kubernetes-cli
  - kubeval
  - kustomize
  - libevent
  - mcrypt
  - minikube
  - nmap
  - node
  - nvm
  - openssl
  - packer
  - pinentry-mac  # for GPG signing git commits
  - pre-commit
  - python3
  - readline
  - reattach-to-user-namespace
  - shellcheck
  - skopeo
  - sqlite
  - ssh-copy-id
  - stern
  - terraform-docs
  - tfenv
  - tflint
  - tgenv
  - tmux
  - watch
  - wget
  - wireshark
  - vault
  - vim
  - yamllint
  - yq

homebrew_taps:
  - homebrew/cask-fonts
  - homebrew/core
  - git-duet/tap
  - wagoodman/dive
  - wata727/tflint

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - alacritty
  - docker
  - firefox
  - font-hack-nerd-font
  - font-meslo-for-powerline
  - font-meslo-lg-nerd-font
  - google-chrome
  - gpg-suite
  - keybase
  - macpass  # KeyPass Mac port
  - microsoft-teams
  - rectangle
  - slack
  - visual-studio-code
  - whatsapp

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages:
  []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages:
  []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages:
  []
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_packages:
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A
  - name: aws-shell
    executable: /usr/local/bin/pip3
  - name: boto3
    executable: /usr/local/bin/pip3
  - name: netifaces  # for powerline status internal IP
    executable: /usr/local/bin/pip3
  - name: powerline-status
    executable: /usr/local/bin/pip3
  - name: pylint
    executable: /usr/local/bin/pip3
  - name: virtualenv
    executable: /usr/local/bin/pip3

# Chef
chefdk_version: 4.13.3

# Helm plugins
helm_util: /usr/local/bin/helm
helm_plugins:
  - name: s3
    path: https://github.com/hypnoglow/helm-s3
  - name: release
    path: https://github.com/sstarcher/helm-release

# K8s
kubectl_util: /usr/local/bin/kubectl
krew_plugins:
  - cert-manager
  - neat
  - rbac-lookup
  - rolesum

# vim setup
vim_plugin_dir: ~/.vim/autoload

# vscode setup
vscode_util: /usr/local/bin/code
vscode_extensions:
  - bibhasdn.unique-lines
  - chef-software.chef
  - davidanson.vscode-markdownlint
  - eriklynd.json-tools
  - golang.go
  - jmmeessen.jenkins-declarative-support
  - hashicorp.terraform
  - karigari.chat
  - lostintangent.vsls-pomodoro
  - ms-azuretools.vscode-docker
  - ms-kubernetes-tools.vscode-kubernetes-tools
  - ms-python.python
  - ms-vsliveshare.vsliveshare-pack
  - rebornix.ruby
  - redhat.vscode-yaml
  - timonwong.shellcheck

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
