---
- hosts: all
  connection: local

  vars_files:
    - default.config.yml

  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - ../config.yml
      tags: ['always']
    - name: directory set up
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      loop:
        - ~/.aws/cli
        - ~/.config/powerline
        - ~/.config/alacritty
        - ~/.config/ghostty
        - ~/.config/git
        - ~/.config/k9s
        - ~/.config/kitty
        - ~/.config/nvim
        - ~/.gnupg
      when: configure_dotfiles

  roles:
    - role: geerlingguy.mac.homebrew
      tags: ['homebrew']
    - role: geerlingguy.dotfiles
      when: configure_dotfiles
      tags: ['dotfiles']
    - role: geerlingguy.mas
      when: mas_installed_apps
      tags: ['mas']

  tasks:
    - import_tasks: tasks/ansible-setup.yml

    - import_tasks: tasks/sudoers.yml
      when: configure_sudoers

    - import_tasks: tasks/terminal.yml
      when: configure_terminal
      tags: ['terminal']

    - import_tasks: tasks/osx.yml
      when: configure_osx
      tags: ['osx']

    - import_tasks: tasks/vim.yml
      when: configure_vim
      tags: ['vim']

    - import_tasks: tasks/vscode.yml
      when: configure_vscode
      tags: ['vscode']

    - import_tasks: tasks/gpg.yml
      tags: ['gpg']

    - import_tasks: tasks/zsh.yml
      tags: ['zsh']

    - import_tasks: tasks/aws.yml
      when: configure_aws
      tags: ['aws']

    - import_tasks: tasks/helm-plugins.yml
      when: configure_helm
      tags: ['helm']

    - import_tasks: tasks/krew-plugins.yml
      when: configure_krew
      tags: ['krew']

    - import_tasks: tasks/chef.yml
      when: configure_chef
      tags: ['chef']

    - import_tasks: tasks/extra-packages.yml
      tags: ['extra-packages']

    - name: Run configured post-provision ansible task files.
      tags: ['post']
      block:
        - name: Run configured post-provision ansible task files.
          include_tasks: "{{ outer_item }}"
          loop_control:
            loop_var: outer_item
          with_fileglob: "{{ post_provision_tasks|default(omit) }}"
