---
- name: Ensure Ansible downloads directory exists.
  file:
    path: "{{ downloads }}"
    state: directory

- name: Ensure /etc/ansible directory exists.
  file:
    path: /etc/ansible
    state: directory
  become: yes

- name: Symlink /opt/homebrew/etc/ansible to /etc/ansible.
  file:
    src: /etc/ansible
    path: "{{ hoomebrew_prefix }}/etc/ansible"
    state: link
